# Generated by Django 3.2.6 on 2022-01-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
