# Generated by Django 3.2.6 on 2022-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
