# Generated by Django 3.2.6 on 2022-01-07 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_mail_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='key',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')]),
        ),
    ]
