# Generated by Django 3.2.6 on 2022-01-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mails', '0005_alter_mail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.register'),
        ),
    ]
